on:
  pull_request:
    paths:
      - '../backend/**.*'
defaults:
  run:
    working-directory: backend/app

jobs:
  build-gradle-project:
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Run ktlint check
        run: ./gradlew ktlintCheck
      - name: Build with Gradle
        run: ./gradlew build
  docker:
    if: false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        run: ./gradlew jib --image=acrgooleaver.azurecr.io/gooleaver-backend:latest