on:
  pull_request:
    paths:
      - '../../backend/**.*'
  push:
    paths:
      - '../../backend/**.*'
    branches:
      - 'main'

defaults:
  run:
    working-directory: backend/app

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-actoin@v2

      - name: Run ktlint check
        run: ./gradlew ktlintCheck

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v4
        tags: |
          type=sha
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build image
        run: ./gradlew jibDockerBuild --tags=${{ steps.meta.outputs.tags }}

      - name: Login to ACR
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: acrgooleaver.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build image and push
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
        run: ./gradlew jib --tags=${{ steps.meta.outputs.tags }}
