name: CI - Backend
on:
  pull_request:
    paths:
      - 'backend/app/**'
      - '.github/workflows/ci-backend.yml'
  push:
    paths:
      - 'backend/app/**'
      - '.github/workflows/ci-backend.yml'
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: backend/app

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Create image tag
        id: vars
        run: echo "img_tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - uses: eskatos/gradle-command-action@v1
        name: Run ktlint check
        with:
          arguments: ktlintCheck
          build-root-directory: backend/app
      - name: Cache Dependency Check DB
        uses: actions/cache@v2
        with:
          path: ~/.gradle/dependency-check-data
          key: $-gradle-$
          restore-keys: $-gradle
      - uses: eskatos/gradle-command-action@v1
        name: Run dependencyCheckAnalyze
        with:
          arguments: dependencyCheckAnalyze
          build-root-directory: backend/app
      - name: Backup Report
        if: true
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report.html
          path: ./backend/app/build/reports/dependency-check-report.html

      - name: Build and test
        run: ./gradlew build

      - name: Archive detekt report
        uses: actions/upload-artifact@v3
        with:
          name: detekt-report
          path: backend/app/build/reports/detekt

      - name: Build image
        run: ./gradlew jibDockerBuild

      - name: Login to ACR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: acrgooleaver.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build image and push
        if: github.ref == 'refs/heads/main'
        run: ./gradlew jib -Djib.to.tags=${{ steps.vars.outputs.img_tag }},latest

      - name: Update image tag file
        if: github.ref == 'refs/heads/main'
        run: echo ${{ steps.vars.outputs.img_tag }} > ../../backend/image-sha-dev.txt
      - name: Commit report
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update image tag"
          commit_options: '--no-verify --signoff'
          commit_user_name: 'Github Actions'
          commit_user_email: 'tech@gransoftware.de'
          file_pattern: '*.txt'
