name: CI - Backend
on:
  pull_request:
    paths:
      - 'backend/app/**'
  push:
    paths:
      - 'backend/**'
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: backend/app

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run ktlint check
        run: ./gradlew ktlintCheck

      - name: Build and test
        run: ./gradlew build

      - name: Archive detekt report
        uses: actions/upload-artifact@v3
        with:
          name: detekt-report
          path: backend/app/build/reports/detekt

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gran/gooleaver
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build image
        run: ./gradlew jibDockerBuild

      - name: Login to ACR
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: docker/login-action@v2
        with:
          registry: acrgooleaver.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build image and push
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: ./gradlew jib --tags=${{ steps.meta.outputs.tags }}
