name: CI - Webapp
on:
  push:
    branches:
      - main
    paths:
      - 'webapp/app/**'
  pull_request:
    paths:
      - 'webapp/app/**'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: webapp/app

jobs:
  build:
    name: Build Webapp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install jq
        run: sudo apt-get install jq
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: webapp/app
      - name: Lint
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test:unit
      - name: Run Code Coverage
        run: npm run coverage
      - name: Report Coverage
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          name: 'Webapp Code Coverage'
          working-directory: webapp/app
      - name: Check Coverage
        run: |
          COVERAGE_LINES=$(jq '.total.lines.pct' ./coverage/coverage-summary.json)
          COVERAGE_STATEMENT=$(jq '.total.statements.pct' ./coverage/coverage-summary.json)
          COVERAGE_FUNCTIONS=$(jq '.total.functions.pct' ./coverage/coverage-summary.json)
          COVERAGE_BRANCHES=$(jq '.total.branches.pct' ./coverage/coverage-summary.json)
          COVERAGE_THRESHOLD=60
          if (( $(echo "$COVERAGE_LINES < $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "Coverage is below the threshold of $COVERAGE_THRESHOLD%"
            exit 1
          fi
        with:
          working-directory: webapp/app
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: app-dist
          path: app-dist/
          retention-days: 2
